services:
  navigo-backend:
    image: henryarrovinproject/navigo-backend
    container_name: navigo-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: ${MONGO_URI}
